live_config_reload = true
import = [
    "~/.config/alacritty/themes/everforest_dark.toml"
]

[font]
size = 12.0

# [font.bold]
# family = "FiraMono Nerd Font"
# style = "Medium"

# [font.normal]
# family = "FiraMono Nerd Font"
# style = "Medium"

[font.normal]
family = "RedHatMono Nerd Font"
style = "Regular"


[font.bold]
family = "RedHatMono Nerd Font"
style = "Medium"

[window]
dynamic_padding = true
decorations = "Buttonless"
# opacity = 0.8
opacity = 0.75


[cursor]
style = { shape = "Block", blinking = "On" }
