
[font]
# size = 9.0
size = 12.0
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "JuliaMono Nerd Font"
style = "Light"

[font.bold]
family = "JuliaMono Nerd Font"
style = "SemiBold"

[window]
dynamic_padding = true
# decorations = "None"
decorations = "Buttonless"
# opacity = 0.83
opacity = 0.8
blur = false


[cursor]
style = { shape = "Block", blinking = "On" }

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/everforest_dark.toml"
]
