live_config_reload = true
import = [
    "~/.config/alacritty/themes/everforest_dark.toml"
]

[font]
# size = 9.0
size = 12.0

# [font.bold]
# family = "FiraMono Nerd Font"
# style = "Medium"

# [font.normal]
# family = "FiraMono Nerd Font"
# style = "Medium"

[font.normal]
family = "RedHatMono Nerd Font"
style = "Regular"


[font.bold]
family = "RedHatMono Nerd Font"
style = "Medium"

[window]
dynamic_padding = true
# decorations = "None"
decorations = "Buttonless"
# opacity = 0.83
opacity = 0.75


[cursor]
style = { shape = "Block", blinking = "On" }
