---
- name: dnf install
  become: yes
  ansible.builtin.dnf:
    name:
      - git
      - tmux
      - alacritty
      - neovim
      - bat
      - fzf
      - tree
      - ripgrep
      #- docker
      #- docker-compose
      - zsh
      - wget
      - curl
      - jq
      - fd-find
      - zoxide
    state: latest

- name: Get Golang latest
  ansible.builtin.get_url:
    url: "https://go.dev/dl/go1.22.1.linux-arm64.tar.gz"
    dest: "/tmp/go1.22.1.linux-arm64.tar.gz"
    mode: "0755"
  register: golang_download

- name: Extract Golang tarball to /opt
  ansible.builtin.shell:
    cmd: "tar -xf /tmp/go1.22.1.linux-arm64.tar.gz -C /opt"
  when: golang_download.changed
  become: yes
