---
- name: dnf install
  become: yes
  ansible.builtin.dnf:
    name:
      - git
      - tmux
      - alacritty
      - neovim
      - bat
      - fzf
      - tree
      - ripgrep
      - docker
      - docker-compose
      - zsh
      - wget
      - curl
      - jq
      - fd
      - golang
    state: latest
  when: ansible_distribution == "Fedora"
