--require("gavin.plugins.snippets")
require("gavin.plugins.autoclose")
require("gavin.plugins.cloak")
require("gavin.plugins.formatter")
require("gavin.plugins.fugitive")
require("gavin.plugins.gitsigns")
require("gavin.plugins.harpoon")
require("gavin.plugins.lsp")
require("gavin.plugins.lualine")
require("gavin.plugins.neogen")
require("gavin.plugins.telescope")
require("gavin.plugins.treesitter")
require("gavin.plugins.trouble")
require("gavin.plugins.undotree")
require("gavin.plugins.vimtmuxnav")
require("gavin.plugins.webdevicons")
-- require("gavin.plugins.codeium")
require("gavin.plugins.adocpreview")
-- require("gavin.plugins.obsidian")
require("gavin.plugins.flutter")
